# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

#Please consult the lectures

#### Major Difference is:

Vector: A Vector is a one-dimensional array (only column vector or only row vector, one at a time) and 

Matrix: Matrix is two-dimensional array (both row and columns) of numbers.

**2. How to import `NumPy` library?** 

In [66]:
# To avoid overwriting the output, please code here 

import numpy

**3. Convert the given Python list into NumPy array and check its data type**

In [67]:
list_1 = [1,2,3,4,5]

In [77]:
# To avoid overwriting the output, please code here 

import numpy as np

numpy_array = np.array(list_1)
numpy_array, type(numpy_array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [78]:
# To avoid overwriting the output, please code here 

np.arange(6)

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

##### 5. Generate an `array of "5" zeros`

In [79]:
# To avoid overwriting the output, please code here 

np.zeros(5)

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [80]:
# To avoid overwriting the output, please code here 

matrix = np.zeros((3, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [81]:
# To avoid overwriting the output, please code here 

print(np.ones(5))

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [82]:
# To avoid overwriting the output, please code here 

tens_array = np.full(5, 10.)
tens_array

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [83]:
# To avoid overwriting the output, please code here 

even_numbers_array = np.arange(52, 100, step=2)
even_numbers_array

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [86]:
# To avoid overwriting the output, please code here 

np.linspace(0, 1, 10, retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [88]:
# To avoid overwriting the output, please code here 

vector_array = np.arange(25)
vector_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [111]:
# To avoid overwriting the output, please code here 

vector_array = np.arange(25)
matrix_2d = vector_array.reshape(5, 5)
matrix_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
matrix_2d_shape = vector_array.reshape((5, 5))
matrix_2d_shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [90]:
# To avoid overwriting the output, please code here 

matrix = np.arange(0.1, 2.6, 0.1)
matrix.reshape(5, 5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [107]:
# To avoid overwriting the output, please code here 

array = numpy.linspace(0, 24, 25, dtype=int) #use linspace()
matrix = array.reshape(5, 5)
print(matrix) #use print()
matrix

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [95]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.


Main difference between linspace() and arange():

1. linspace() allows to specify the number of steps and return set of samples with a given interval.
2. arange() allows to specify the size of the steps and return values with in a range which has a space between values.

**15. How to generate a single random integer number using NumPy built-in function?**

In [100]:
# To avoid overwriting the output, please code here 

random_number = np.random.randint(0, 10)
random_number

8

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [103]:
# To avoid overwriting the output, please code here 

random_matrix = (np.random.rand(7, 5) * 35).astype(float)
print(random_matrix)

[[18.92082745 18.25883102  5.38887464 26.2428744   3.84203872]
 [ 3.01707664 29.21541675 12.68522162 17.05220114 29.09813161]
 [10.18540515  4.54093825 22.69084905  3.96986274 24.12704216]
 [28.53879173 31.91164216  3.81008097 24.44207217  2.68541844]
 [18.80834858 20.47536299 12.31676652 21.10150926  8.30032601]
 [ 9.29415287 21.6543442  17.17296389 17.42190951 30.9797326 ]
 [31.99908503 26.68526362  8.18367569 25.65462454 17.57487435]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [106]:
# To avoid overwriting the output, please code here 

identity_matrix = np.eye(5) * 5
identity_matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 